feat: добавил Service Worker
egtalovikov/crazy-kitchen pull request #22
Opened 2023-09-09 15:07 UTC by egtalovikov

2023-09-09 16:26 UTC, Evgenia1394 approved these changes

2023-09-10 06:45 UTC, IvanPeleshok commented on packages/client/public/sw.js
> +      .then(cache => {
Предлагаю писать асинхронный код в плоском стиле с помощью async / await + try / catch
https://javascript.info/async-await

2023-09-10 06:46 UTC, IvanPeleshok requested changes
Замечательная работа!
Всё гуд, но предлагаю колбеки переписать на await

2023-09-10 13:49 UTC, IvanPeleshok commented on packages/client/src/main.tsx
> +        .then(registration => {
Тут тоже хотелось бы видеть async / await :)

2023-09-10 13:50 UTC, IvanPeleshok approved these changes
Критических замечаний нет :)
Работа принята!

2023-09-10 13:50 UTC, merged