feature/ck-38
egtalovikov/crazy-kitchen pull request #34
Opened 2023-10-04 18:33 UTC by Evgenia1394

### Какую задачу решаем
https://linear.app/crazy-kitchen/issue/CK-38/dobavit-api-dlya-liderborda

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-10-05 07:03 UTC, IvanPeleshok commented on packages/client/src/api/leaderBoard/index.ts
> +    teamName: 'crazyKitchen',
Можно использовать константу teamName

2023-10-05 07:04 UTC, IvanPeleshok commented on packages/client/src/api/leaderBoard/index.ts
> +export interface Player {
Возможно есть смысл вынести в отдельный модуль интерфейс Player и переиспользовать в дальнейшем при необходимости

2023-10-05 07:07 UTC, IvanPeleshok commented on packages/client/src/pages/LeaderBoard/index.tsx
> +    getLeaderBoard()
Предлагаю использовать последний синтаксис языка и обрабатывать промиссы с помощью async / await + try / catch
```
useEffect(() => {
  const request = async () => {
    try {
      const players = await getLeaderBoard()
      setPlayers(players)
    } catch (error) {
      console.log(error)
    }
    
    request()
  }

}, [])
```

2023-10-05 07:09 UTC, IvanPeleshok commented on packages/client/src/pages/LeaderBoard/index.tsx
> +            players.map((player: Player) => (
Достаточно только players.map

2023-10-05 07:10 UTC, IvanPeleshok commented on packages/client/src/pages/LeaderBoard/index.tsx
> +                style={{
Для чего инлайн стили? Предлагаю всё указывать в правилах css

2023-10-05 07:11 UTC, IvanPeleshok commented on packages/client/src/api/leaderBoard/index.ts
> +) => {
Есть возможность указать возвращаемый тип?

2023-10-05 07:12 UTC, IvanPeleshok requested changes
Проделана огромная работа!
Есть небольшие замечания, необходима доработка

2023-10-05 19:32 UTC, Evgenia1394 commented on packages/client/src/pages/LeaderBoard/index.tsx
> +                style={{
убрала, но в данном месте не получалось перебить стиль ListItem justifyContent: 'flex-start' на 'space-between' потому пришлось тут оставить

2023-10-06 09:22 UTC, IvanPeleshok commented on packages/client/src/pages/LeaderBoard/index.tsx
> +                style={{
Почему не удалось?
Возможно это поможет в дальнейшем перебивать правила: https://ru.hexlet.io/courses/layout-designer-basics/lessons/css-cascade/theory_unit
https://metanit.com/web/html5/5.10.php

2023-10-06 09:23 UTC, IvanPeleshok approved these changes
Поздравляю, работа принята!
Отлично постарались)

Хорошего дня :)

2023-10-06 10:38 UTC, egtalovikov approved these changes

2023-10-06 19:21 UTC, merged