add smiles
egtalovikov/crazy-kitchen pull request #41
Opened 2023-10-15 11:29 UTC by malykhs1

### Какую задачу решаем
Добавить эмодзи в проект (клиентская часть)

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-10-15 12:32 UTC, catyakaz approved these changes

2023-10-15 15:00 UTC, Evgenia1394 approved these changes

2023-10-15 15:02 UTC, Evgenia1394 approved these changes

2023-10-15 19:39 UTC, IvanPeleshok commented on packages/client/src/components/AddCommentForm/index.tsx
> +  const renderEmojies = () => {
Предлагаю вынести в отдельный компонент, добавив декомпозиции компонентов

2023-10-15 19:40 UTC, IvanPeleshok commented on packages/client/src/components/AddCommentForm/index.tsx
> +          style={{ marginRight: '5px' }}
Для какой цели писать инлайн стили, когда есть правила в css?

2023-10-15 19:42 UTC, IvanPeleshok commented on packages/client/src/components/AddCommentForm/index.tsx
> +        className={`${styles.popup} ${isOpen ? styles['popup_open'] : ''} ${
Предлагаю воспользоваться classNames
Пример:
```
<div className={classnames('container', {
   'success': success, // if success={true}, 'success' is added
   'alert': alert,
   'normal': normal,
})} />
```

https://medium.com/2359media/why-react-classnames-is-a-lifesaver-and-how-you-should-use-it-if-you-arent-already-b25a44ed5603

2023-10-15 19:44 UTC, IvanPeleshok commented on packages/client/src/components/TopicReaction/index.tsx
> +    newReactions[emoji!] = (newReactions[emoji!] || 0) + 1
Надежнее было бы написать следующим образом:
```
if (emoji) {
  ...
}
```

2023-10-15 19:45 UTC, IvanPeleshok commented on packages/client/src/components/TopicReaction/index.tsx
> +  const renderEmojies = () => {
Выносим в отдельный модуль и переиспользуем (замитил этот компонент в двух местах)

2023-10-15 19:46 UTC, IvanPeleshok commented on packages/client/src/__mocks__/EmojiList.ts
> +export default [
Замечательно, что вынесли в отдельный молуль

2023-10-15 19:47 UTC, IvanPeleshok commented on packages/client/src/components/AddCommentForm/index.tsx
> +          onClick={e => handlerButtonClick(e)}
Предлагаю передавать ссылку на функцию, а не колбек
onClick={handlerButtonClick}

2023-10-15 19:47 UTC, IvanPeleshok requested changes
Проделана огромная работа!
Отлично постарались!

Есть небольшие замечания, предлагаю доработать
Важно поправить линтер

Хорошего дня 🚀

2023-10-16 16:31 UTC, malykhs1 commented
1. Рендрер эмодзи переписал и добавил отдельный компонент, убрав дублирование кода. 
2. Ошибки линтера пофиксил
3. Поправил по остальным комментариям. 
P.s. прикольная либа для classnames, первый раз о ней слышу.

2023-10-17 13:00 UTC, IvanPeleshok commented
> 1. Рендрер эмодзи переписал и добавил отдельный компонент, убрав дублирование кода.
> 2. Ошибки линтера пофиксил
> 3. Поправил по остальным комментариям.
>    P.s. прикольная либа для classnames, первый раз о ней слышу.

Если работа готова, то предлагаю её сдать на проверку :)

2023-10-17 14:30 UTC, malykhs1 commented
> > 1. Рендрер эмодзи переписал и добавил отдельный компонент, убрав дублирование кода.
> > 2. Ошибки линтера пофиксил
> > 3. Поправил по остальным комментариям.
> >    P.s. прикольная либа для classnames, первый раз о ней слышу.
> 
> @malykhs1 Если работа готова, то предлагаю её сдать на проверку :)

Чисто мой косяк @IvanPeleshok . Отправил еще раз.

2023-10-18 11:47 UTC, IvanPeleshok commented on packages/client/src/components/AddCommentForm/index.tsx
> +        className={classNames(
Здесь предполагалось следующее:
```
className={classNames(
  styles.popup,
  styles[popup_bottom,
  [styles.popup_open]: isOpen
```

2023-10-18 11:49 UTC, IvanPeleshok approved these changes
Отлично потрудились!

Поздравляю, работа приянта!

Хорошего дня :)

2023-10-24 08:11 UTC, merged