Feature/ck 19
egtalovikov/crazy-kitchen pull request #6
Opened 2023-08-20 16:10 UTC by catyakaz

### Какую задачу решаем

https://linear.app/crazy-kitchen/issue/CK-19/sverstat-stranicu-registracii
### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-08-22 09:49 UTC, egtalovikov requested changes

2023-08-22 09:49 UTC, egtalovikov commented on packages/client/src/pages/SignUp/index.tsx
> +                  name="last_name"
Поле по ТЗ должно быть "second_name"

2023-08-22 09:50 UTC, egtalovikov commented
Пофиксить поле, конфликт и вливаем :)

2023-08-22 15:05 UTC, catyakaz commented on packages/client/src/pages/SignUp/index.tsx
> +                  name="last_name"
да, спасибо что заметил, поправила это в след пр

2023-08-25 06:15 UTC, egtalovikov approved these changes

2023-08-25 06:15 UTC, merged