Feature/ck 16
egtalovikov/crazy-kitchen pull request #7
Opened 2023-08-22 15:44 UTC by catyakaz

### Какую задачу решаем
https://linear.app/crazy-kitchen/issue/CK-16/realizovat-logiku-avtorizacii

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-08-25 09:56 UTC, egtalovikov commented on packages/client/src/api/auth/auth.types.ts
> +export interface SignUpData {
Здесь не лучше будет расширить SignInData? Чтобы не дублировать два поля

2023-08-25 09:56 UTC, egtalovikov submitted a review, later dismissed

2023-08-25 12:10 UTC, egtalovikov submitted a review, later dismissed

2023-08-25 20:06 UTC, IvanPeleshok commented on packages/client/src/api/auth/index.ts
> +const BASE_URL = 'https://ya-praktikum.tech/api/v2/auth'
Предлагаю вынести в переменные окружения (env)
https://habr.com/ru/companies/ruvds/articles/351254/

2023-08-25 20:08 UTC, IvanPeleshok commented on packages/client/src/api/auth/index.ts
> +    } = await axios.post(
Предлагаю настроить в один месте axios с помощью метода create и использовать его в дальнейшем, так будет удобнее

Пример: https://axios-http.com/ru/docs/config_defaults
Можно поискать ещё, в стеке реакта к примеру

2023-08-25 20:10 UTC, IvanPeleshok commented on packages/client/src/main.tsx
> +store.dispatch(fetchUserData())
Данный метод лучше вызвать в компоненте App в рамках хука useEffector с пустым массивом зависимостей
https://stackoverflow.com/questions/58579426/in-useeffect-whats-the-difference-between-providing-no-dependency-array-and-an

2023-08-25 20:11 UTC, IvanPeleshok commented on packages/client/src/pages/SignIn/useSignIn.ts
> +    postSignIn(signInData)
Используем async / await + try / catch
Остовляем код плоским

2023-08-25 20:12 UTC, IvanPeleshok commented on packages/client/src/pages/SignUp/useSignUp.ts
> +    postSignUp(signUpData)
async / await + try / catch

2023-08-25 20:13 UTC, IvanPeleshok requested changes
Была проделана большая работа
Всё замечательно, но есть несколько замечаний

2023-08-25 20:13 UTC, IvanPeleshok commented on packages/client/src/store/modules/auth/auth.reducer.ts
> +      ;(state.id = payload.id),
; лишняя

2023-08-25 20:14 UTC, IvanPeleshok commented on packages/client/src/store/modules/auth/auth.reducer.ts
> +  return await getUserInfo()
return await обычно не пишут, следует разделять 
```
const response = await request()
return reponse
```

2023-08-25 20:16 UTC, IvanPeleshok commented on packages/client/src/store/modules/auth/auth.selector.ts
> +export const authorizedStatusSelector = (state: {
Предлагаю обратить внимание на https://redux.js.org/usage/deriving-data-selectors
Такие селекторы будут с оптимизацией

2023-08-25 20:17 UTC, IvanPeleshok commented on packages/client/src/store/modules/auth/auth.reducer.ts
> +      ;(state.id = payload.id),
Для чего выражения обёрнуты в скобки?

2023-08-27 22:14 UTC, IvanPeleshok approved these changes
Всё замечательно, апрув :)

2023-08-28 06:04 UTC, Evgenia1394 approved these changes

2023-08-28 09:12 UTC, malykhs1 commented
Ребят, вижу что есть апрув. Сливаю с основной веткой, чтобы дописать валидацию!

2023-08-28 09:12 UTC, merged