Сверстана страница пользователя, реализована логика смены пароля и аватара
egtalovikov/crazy-kitchen pull request #8
Opened 2023-08-25 09:19 UTC by egtalovikov

### Какую задачу решаем

https://linear.app/crazy-kitchen/issue/CK-22/sverstat-stranicu-polzovatelya

2023-08-25 11:44 UTC, catyakaz reviewed
чтобы брать данные из стора ты можешь сделать ответвление от моей ветки со стором

2023-08-25 11:44 UTC, catyakaz commented on packages/client/src/api/user/index.ts
> +}
давай создадим папку user и занесем туда все запросы, аналогично моей структуре, чтобы было легче потом мерджить

2023-08-25 11:44 UTC, catyakaz commented on packages/client/src/components/modals/ChangeAvatar/index.tsx
> +  }
вынеси всю логику в кастомный хук

2023-08-25 11:44 UTC, catyakaz commented on packages/client/src/components/modals/ChangeAvatar/index.tsx
> +        setAvatar(undefined)
лучше перенести setAvatar в стор

2023-08-25 11:44 UTC, catyakaz commented on packages/client/src/components/modals/ChangePassword/index.tsx
> +
вынеси всю логику в кастомный хук

2023-08-25 11:44 UTC, catyakaz commented on packages/client/src/pages/Profile/index.tsx
> +
вынеси всю логику в кастомный хук + можно брать данные по юзеру из стора

2023-08-25 12:01 UTC, egtalovikov commented on packages/client/src/api/user/index.ts
> +}
У меня же в ней и лежит)

2023-08-25 12:01 UTC, egtalovikov commented on packages/client/src/api/user/index.ts
> +}
У меня же в ней и лежит)

2023-08-25 12:03 UTC, catyakaz commented on packages/client/src/api/user/index.ts
> +}
прости пожалуйста, не заметила

2023-08-25 12:03 UTC, egtalovikov commented on packages/client/src/components/modals/ChangeAvatar/index.tsx
> +  }
А зачем? У нас же больше нигде эта логика не будет использоваться

2023-08-25 12:04 UTC, egtalovikov commented on packages/client/src/components/modals/ChangeAvatar/index.tsx
> +        setAvatar(undefined)
Я решил не делать пока ничего со стором, чтобы ревьюеру было проще. Задача на внедрение стора, c 6 спринта)

2023-08-25 12:06 UTC, catyakaz commented on packages/client/src/components/modals/ChangeAvatar/index.tsx
> +  }
я так поняла что по моим пр ты был не против писать всю логику для компонента в хуках для этого компонента, а в самом компоненте рендерить только компонент, чтобы ничего не мешалось

2023-08-25 12:09 UTC, egtalovikov commented on packages/client/src/pages/Profile/index.tsx
> +
И тут не понимаю :) По стору всё так же, подключу в 6 спринте)

2023-08-25 12:27 UTC, egtalovikov commented on packages/client/src/components/modals/ChangeAvatar/index.tsx
> +  }
Мне просто кажется, если логика не переиспользуется, то кастомный хук не нужен) Предлагаю тогда потом обсудить кодстайл с командой, придём к одному решению, как будем писать и создадим таску на рефакторинг на доработках :)

2023-08-25 12:34 UTC, catyakaz approved these changes

2023-08-25 20:35 UTC, IvanPeleshok commented on .gitignore
> +.DS_Store
Предлагаю добавлять пустую строку в конце файла
Автоматически настраивается в vscode за 2 минуты)

https://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file

2023-08-25 20:37 UTC, IvanPeleshok commented on packages/client/src/components/modals/ChangeAvatar/index.tsx
> +      changeAvatar(avatar).then(data => {
Используем async / await, оставляя код плоским
Обязательно используем try / catch для того, чтобы обработать ошибку

2023-08-25 20:38 UTC, IvanPeleshok commented on packages/client/src/components/modals/ChangeAvatar/index.tsx
> +}
Между блоками всегда пустая строка (поправить по всём PR)

2023-08-25 20:38 UTC, IvanPeleshok commented on packages/client/src/components/modals/ChangeAvatar/index.tsx
> +type User = {
Вынести в отдельный модуль, так как предполагаю, что это можно переиспользовать где-то ещё

2023-08-25 20:40 UTC, IvanPeleshok commented on packages/client/src/components/modals/ChangeAvatar/index.tsx
> +              onChange={e => {
Не пишем инлайн колбеки, выносим их в функции, сюда передаём ссылку
```
const onChange = (ev: ТИП (ОБЯЗАТЕЛЬНО) => {})

return (
  <input onChange={onChange) />
)
```

2023-08-25 20:41 UTC, IvanPeleshok commented on packages/client/src/components/modals/ChangePassword/index.tsx
> +    changePassword({
Используем async / await
Обрабатываем ошибки с помощью try / catch

2023-08-25 20:42 UTC, IvanPeleshok commented on packages/client/src/pages/Profile/Profile.module.scss
> +}
Пустая строка в конце файла

2023-08-25 20:42 UTC, IvanPeleshok commented on packages/client/src/pages/Profile/index.tsx
> +    getUserInfo().then(data => setUser(data))
async / await + try / catch

2023-08-25 20:43 UTC, IvanPeleshok commented on packages/client/src/pages/Profile/index.tsx
> +              user.avatar ? REACT_APP_API_URL + 'resources' + user.avatar : ''
Предлагаю вынести в переменную и использовать её тут

2023-08-25 20:45 UTC, IvanPeleshok commented on packages/client/src/pages/Profile/index.tsx
> +  return (
Рекомендация: стараться декомпозировать повторяющиеся элементы, максимально переиспользовав
Легче тестировать и читать, проще масштабироваться

2023-08-25 20:46 UTC, IvanPeleshok commented on packages/client/src/utils/consts.ts
> +export const REACT_APP_API_URL = 'https://ya-praktikum.tech/api/v2/'
Такие элементы лучше выносить в переменные окружения
Проще будет работать при развёртовании

2023-08-25 20:48 UTC, IvanPeleshok requested changes
Проделана огромная работа, но есть небольшие замечания

Предлагаю с ними ознакомиться и поправить

2023-08-28 18:53 UTC, IvanPeleshok commented on packages/client/src/pages/Profile/index.tsx
> +    void fetchUser()
Очень редко вижу вызов void fn()
Предлагаю не использовать подобный синтаксис, не очень понимаю бенефиты
Проще вернуть return в конце функции, коллеги оценят

2023-08-28 18:54 UTC, IvanPeleshok approved these changes
Всё замечательно, апрув
Хорошо потрудился :)

2023-08-28 20:41 UTC, merged